name: Python Unittests
on:
  pull_request:
    paths: [ 'src/**', '.github/**' ]
  push: { branches: main }

jobs:
  test_data_models:
    name: Run python unittests for nuc2seg
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run tests
        run: make python-unittest
