name: Spatialdata Container
on:
  pull_request:
    paths: ['containers/spatialdata/**']
  push: { branches: main }

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push container
        uses: docker/build-push-action@v3
        with:
          context: containers/spatialdata
          file: containers/spatialdata/Dockerfile
          push: true
          tags: |
            jeffquinnmsk/spatialdata:latest
            jeffquinnmsk/spatialdata:${{ github.sha }}
          cache-from: type=registry,ref=jeffquinnmsk/spatialdata:latest
